# Generated by Django 3.2.8 on 2021-11-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_packagemodel_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containermodel',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
