# Generated by Django 3.2.8 on 2021-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_containermodel_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMeanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('co2_normal_center', models.FloatField(default=10)),
                ('co2_normal_count', models.IntegerField(default=0)),
                ('co2_abnormal_center', models.FloatField(default=0)),
                ('co2_abnormal_count', models.IntegerField(default=0)),
                ('vibration_normal_center', models.FloatField(default=10)),
                ('vibration_normal_count', models.IntegerField(default=0)),
                ('vibration_abnormal_center', models.FloatField(default=0)),
                ('vibration_abnormal_count', models.IntegerField(default=0)),
                ('humidity_normal_center', models.FloatField(default=10)),
                ('humidity_normal_count', models.IntegerField(default=0)),
                ('humidity_abnormal_center', models.FloatField(default=0)),
                ('humidity_abnormal_count', models.IntegerField(default=0)),
                ('temperature_normal_center', models.FloatField(default=10)),
                ('temperature_normal_count', models.IntegerField(default=0)),
                ('temperature_abnormal_center', models.FloatField(default=0)),
                ('temperature_abnormal_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='desciption',
            new_name='description',
        ),
    ]
