# Generated by Django 3.2.9 on 2021-11-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20211102_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmeanmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='kmeanmodel',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='co2_abnormal_center',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='co2_normal_center',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='humidity_abnormal_center',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='humidity_normal_center',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='temperature_abnormal_center',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='temperature_normal_center',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='vibration_abnormal_center',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='vibration_normal_center',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
