# Generated by Django 3.2.8 on 2021-11-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20211102_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmeanmodel',
            name='co2_normal_center',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='humidity_normal_center',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='temperature_normal_center',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='vibration_normal_center',
            field=models.FloatField(default=0),
        ),
    ]
