# Generated by Django 3.2.9 on 2021-11-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20211103_0811'),
        ('apps', '0005_auto_20211105_1135'),
    ]

    operations = [
    ]
