# Generated by Django 3.2.9 on 2021-11-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_kmeanmodel_co2_normal_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmeanmodel',
            name='co2_abnormal_center',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='co2_normal_center',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='humidity_abnormal_center',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='humidity_normal_center',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='temperature_abnormal_center',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='temperature_normal_center',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='vibration_abnormal_center',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='kmeanmodel',
            name='vibration_normal_center',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
