# Generated by Django 3.2.9 on 2021-11-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20211108_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='expect',
            field=models.JSONField(default={'co2': 400, 'humidity': 88, 'temp': 26, 'vibration': 0}),
        ),
    ]
